name: diplom_fl
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  http: ^1.0.0
  google_fonts: ^6.2.1
  path_provider: ^2.1.5
  shared_preferences: ^2.2.2
  hydrated_bloc: ^10.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
flutter:
  uses-material-design: true

  assets:
    - assets/fitnes.png
    - assets/widgets.json
    - assets/GYMAPP.png
    - assets/logo.png